---
resource_groups1:
  "rg01":
    location: "One"
    tags:
      description: "this is a test resource group"
  "rg02":
    location: "Two"
    tags:
      description: "This is a second resource group"                                       
